// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pipe.proto

package io.data.pipe;

public interface DataResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pipe.DataResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string data = 1;</code>
   */
  java.lang.String getData();
  /**
   * <code>string data = 1;</code>
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
