// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pipe.proto

package io.data.pipe;

public final class DataPipeProto {
  private DataPipeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pipe_DataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pipe_DataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pipe_DataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pipe_DataResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\npipe.proto\022\004pipe\"\033\n\013DataRequest\022\014\n\004dat" +
      "a\030\001 \001(\t\"\034\n\014DataResponse\022\014\n\004data\030\001 \001(\t28\n" +
      "\005Piper\022/\n\004Send\022\021.pipe.DataRequest\032\022.pipe" +
      ".DataResponse\"\000B$\n\014io.data.pipeB\rDataPip" +
      "eProtoP\001\242\002\002DPb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_pipe_DataRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pipe_DataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pipe_DataRequest_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_pipe_DataResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pipe_DataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pipe_DataResponse_descriptor,
        new java.lang.String[] { "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
